version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    volumes:
      - postgres-data:/var/lib/postgressql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
