name: "STG環境コンテナリリース"
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SET env.BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / _)" >> $GITHUB_ENV

      - name: SET env.SERVICE
        run: echo "STG_REEDU_ECS_SERVICE=${{ github.event.inputs.target }}" >> $GITHUB_ENV

      - name: Show inputs
        run: |
          echo "branch_name: ${{ env.BRANCH }}"
          echo "target: ${{ github.event.inputs.target }}"
          echo "service_name: ${{ env.STG_REEDU_ECS_SERVICE }}"
          echo "message: ${{ github.event.inputs.message }}"
