name: "Deploy AWS ECS"

on: [push]
jobs:
  deploy-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: SET env.BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / _)" >> $GITHUB_ENV